
// calendar
export const SET_DATE_OBJECT = 'CALENDAR/SET_DATE_OBJECT';
export const SELECT_DAY = 'CALENDAR/SELECT_DAY';
export const SET_TYPE_CONTENT = 'CALENDAR/TYPE_CONTENT';
export const SET_ALL_MONTHS = 'CALENDAR/ALL_MONTHS';


// reminder
export const SET_NEW_REMINDER = 'REMINDER/SET_NEW_REMINDER';
export const SHOW_MODAL_REMINDER = 'REMINDER/SHOW_MODAL_REMINDER';
export const SET_TYPE_MODAL_REMINDER = 'REMINDER/SET_TYPE_MODAL_REMINDER';
export const UPDATE_REMINDER = 'REMINDER/UPDATE_REMINDER';
export const SET_CURRENT_REMINDER = 'REMINDER/SET_CURRENT_REMINDER';
export const GET_CITY_WEATHER = 'REMINDER/GET_CITY_WEATHER';
export const SET_CITY_WEATHER_ASYNC = 'REMINDER/SET_CITY_WEATHER_ASYNC';
export const SET_ERROR_REMINDER_ASYNC = 'REMINDER/SET_ERROR_REMINDER_ASYNC';